trigger:
  batch: true
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  vsix: '$(Build.SourcesDirectory)\src\GtmExtension\bin\Release\GtmExtension.vsix'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    vsVersion: 16.0
    msbuildArgs: /p:DeployExtension=false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(vsix)' 
    ArtifactName: '$(system.teamProject)'

- task: PowerShell@2
  inputs:
    filePath: '$(Build.SourcesDirectory)\scripts\GetVersion.ps1'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: github
    tagSource: manual
    tag: 'v$(vsix.version)'
    title: 'Version $(vsix.version)'
    assets: '$(vsix)'
